directories:
  output: release
  buildResources: public
extends: null
appId: com.opentalent.app
productName: OpenTalent
files:
  - filter:
      - dist/**/*
      - build/**/*
      - node_modules/**/*
extraMetadata:
  main: dist/main/main.js
electronVersion: 28.3.3
